### ISSUE TITLE
Cannot obtain latest version 3.1.1

### ISSUE THREAD

**Issue by AkishiKato** [3-manifolds/SnapPy#107]
I tried to install the latest version of SnapPy for Windows. I followed the instruction  https://snappy.computop.org/installing.html.
But the opening window says "Please upgrade to 3.1.1 from 3.1 via .....". What's wrong?

**Comment by NathanDunfield** [comment]
@AkishiKato I just uploaded an actual version of SnapPy 3.1.1 for Windows.  If you download the installer again and reinstall, the message should go away.  Thanks again for reporting this.

@culler The problem was actually that, while I did upload a new installer when doing the 3.1.1 release, it was built against the wrong branch of the SnapPy repo...
